---
exclude: ^docs/conf.py
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: pretty-format-json
            name: Pretty format JSON
            args:
                - --no-sort-keys
                - --autofix
                - --indent=2
          - id: trailing-whitespace
            name: Fix trailing whitespace
            exclude: setup.cfg
          - id: check-added-large-files
          - id: end-of-file-fixer
            name: Fix missing EOF
            exclude: setup.cfg
          - id: check-executables-have-shebangs
            name: Check exeutables for shebangs
          - id: check-merge-conflict
            name: Check for merge conflict fragments
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: check-case-conflict
          - id: requirements-txt-fixer
            name: Check for filesystem character case conflicts
          - id: detect-private-key
            name: Check for cleartext private keys stored
          - id: mixed-line-ending
            args: [--fix=no]
          - id: flake8
            additional_dependencies:
                - flake8-mutable
                - flake8-type-annotations
                - flake8-eradicate
                - flake8-bugbear
            name: Check for Python style guideline violations
          - id: check-json
            name: Validate JSON
          - id: check-ast
            name: Check Python abstract syntax tree
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11 # or specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v1.8.0
      hooks:
          - id: reorder-python-imports
            name: Reorder Python imports
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.4.4
      hooks:
          - id: autopep8
            name: Pretty format Python
    - repo: https://github.com/psf/black
      rev: stable
      hooks:
          - id: black
            name: Ruthlessly format Python
            language_version: python3.8
    # - repo: https://github.com/pre-commit/mirrors-isort
    #   rev: v4.3.4
    #   hooks:
    #       - id: isort
    - repo: git@github.com:macisamuele/language-formatters-pre-commit-hooks
      rev: v1.5.0
      hooks:
          - id: pretty-format-toml
            args: [--autofix]
          - id: pretty-format-toml
            args: [--autofix]
