[tool.autopep8]
in-place = true
aggressive = true
experimental = true
max-line-length = 120
remove-all-unused-imports = true
ignore-init-module-imports = true
remove-unused-variable = true
ignore = [ "E231",]

[tool.black]
line-length = 120
include = "\\.pyi?$"
exclude = "(\n  /(\n      \\.eggs         # exclude a few common directories in the\n    | \\.git          # root of the project\n    | \\.hg\n    | \\.mypy_cache\n    | \\.tox\n    | \\.venv\n    | _build\n    | buck-out\n    | build\n    | dist\n  )/\n  | foo.py           # also separately exclude a file named foo.py in\n                     # the root of the project\n)\n"

[tool.check-manifest]
ignore = [ "PKG-INFO", "*.egg-info", "*.egg-info/*", "setup.cfg", ".hgtags", ".hgsigs", ".hgignore", ".gitignore", ".bzrignore", ".gitattributes", ".github/*", ".travis.yml", "Jenkinsfile", "*.mo",]
