---
# This is a basic workflow to help you get started with Actions

name: EVA4 Phase2 Week3

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    build:
    # The type of runner that the job will run on
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: week3
        strategy:
            matrix:
                node-version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm install
            - name: Download Model Artifacts
              run: |
                wget https://github.com/davisking/dlib-models/raw/master/shape_predictor_5_face_landmarks.dat.bz2 -P ./model/shape_predictor_5_face_landmarks.dat.bz2
                wget https://github.com/davisking/dlib-models/raw/master/shape_predictor_68_face_landmarks.dat.bz2 -P ./model/shape_predictor_68_face_landmarks.dat.bz2
                wget https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml -P ./model/haarcascade_frontalface_default.xml
                wget https://github.com/EVA4-RS-Group/Phase2/releases/download/s2/3M-KN95-9501-Dust-Mask_v1.jpg -P ./data/3M-KN95-9501-Dust-Mask_v1.jpg
                bzip2 -dk ./model/shape_predictor_5_face_landmarks.dat.bz2
                bzip2 -dk ./model/shape_predictor_68_face_landmarks.dat.bz2
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1
            - name: Serverless Deploy
              run: npm run-script deploy
